os: osx
osx_image: xcode14.1
language: swift
script: 
  - xcodebuild clean build test -project Recap.xcodeproj -scheme "RecapTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test -project Recap.xcodeproj -scheme "RecapTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iPhone 8" ONLY_ACTIVE_ARCH=YES
